### ISSUE TITLE
Python 3.5 Bug: No need to import izip

### ISSUE THREAD

**Issue by dvf** [bmuller/kademlia#40]
Firstly, thanks for the wonderful reference implementation!

```
dvf@ubuntu-us-nyc-01:~ twistd -noy server.tac 
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/usr/local/lib/python3.5/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 445, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/application/app.py", line 456, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python3.5/dist-packages/twisted/application/service.py", line 412, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python3.5/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "server.tac", line 7, in <module>
    from kademlia.network import Server
  File "/usr/local/lib/python3.5/dist-packages/kademlia/network.py", line 13, in <module>
    from kademlia.storage import ForgetfulStorage
  File "/usr/local/lib/python3.5/dist-packages/kademlia/storage.py", line 2, in <module>
    from itertools import izip
builtins.ImportError: cannot import name 'izip'
```

Since Twisted supports 3.6, how about:

```
try:
    from itertools import izip
except ImportError:
    from itertools import zip
...
```

**Comment by bmuller** [comment]
There's a python 3.5 branch that doesn't use Twisted, I recommend just using that.  I don't think I'll be supporting 2.7 or Twisted going forward.

**Comment by dvf** [comment]
Awesome. I didn't see that. Thanks @bmuller 

Are there any plans to add the Python 3 build to pypi?

**Comment by bmuller** [comment]
Yep!  Just added.
