### ISSUE TITLE
Error when running first_node.py from command line

### ISSUE THREAD

**Issue by FoteinosMerg** [bmuller/kademlia#67]
```shell
...$ python3.6 first_node.py 
2019-02-03 21:49:39,816 - kademlia.network - INFO - Node 92115567338729139094396247980566258409520920742 listening on 0.0.0.0:5678
2019-02-03 21:49:39,817 - kademlia.network - DEBUG - Refreshing routing table
Traceback (most recent call last):
  File "first_node.py", line 18, in <module>
    loop.run_until_complete(server.listen(5678))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 452, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 526, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```
Same issue with the README example (ommiting the `node_bootstrap` line). I'm not able to see what the problem with `loop.run_until_complete` is, Thank You.

**Comment by bmuller** [comment]
Yeah - this was due to a change in the API in `master` that was reflected in the README, but wasn't yet part of a release.  I just made another release on pypi, if you update your local package you should be good.
